repos:
    - repo: git://github.com/golangci/golangci-lint
      rev: v1.31.0
      hooks:
        - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --pattern, '\d\.\d\.\d']
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
